# Generated by Django 5.0.6 on 2024-08-14 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0022_alter_booking_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='workout',
        ),
        migrations.AddField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='gym_app.workoutschedule'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.ManyToManyField(related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
