# Generated by Django 5.0.6 on 2024-08-25 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0023_remove_booking_workout_booking_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='gym_app.workoutschedule'),
        ),
    ]
