# Generated by Django 5.0.6 on 2024-09-22 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0024_alter_booking_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutschedule',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_app.booking'),
        ),
    ]
