# Generated by Django 5.0.6 on 2024-09-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0026_workoutsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutSession',
        ),
    ]
