# Generated by Django 5.0.6 on 2024-09-22 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0027_delete_workoutsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutschedule',
            name='booking',
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='participants',
            field=models.ManyToManyField(related_name='workout_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
