# Generated by Django 5.0.6 on 2024-09-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0028_remove_workoutschedule_booking_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
