# Generated by Django 5.0.6 on 2024-09-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0029_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutschedule',
            name='complet',
            field=models.BooleanField(default=False),
        ),
    ]
