# Generated by Django 5.0.6 on 2024-09-30 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0030_workoutschedule_complet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.workoutschedule')),
            ],
            options={
                'unique_together': {('workout_schedule', 'participant')},
            },
        ),
    ]
