# Generated by Django 5.0.6 on 2024-10-02 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0032_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_company', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('catalog_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.catalogservice')),
            ],
        ),
        migrations.CreateModel(
            name='GymAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('catalog_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.catalogservice')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalizedCoaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('catalog_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.catalogservice')),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'Coach'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
