# Generated by Django 5.1.2 on 2024-10-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0033_catalogservice_dietplan_gymaccessory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
