# Generated by Django 5.1.2 on 2024-10-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0034_message_is_archived_message_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
