# Generated by Django 5.1.2 on 2024-11-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0038_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
