# Generated by Django 4.2 on 2024-12-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0040_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='unavailable_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='unavailable_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='unavailable_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
