# Generated by Django 4.2 on 2024-12-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0041_coach_unavailable_from_coach_unavailable_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='leave_requests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='leave_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=10),
        ),
    ]
